---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backuppc
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backuppc
  template:
    metadata:
      labels:
        app: backuppc
    spec:
      serviceAccountName: backuppc
      containers:
        - name: backuppc
          env:
          - name: BACKUPPC_UUID
            value: "1000"
          - name: BACKUPPC_GUID
            value: "1000"
          - name: BACKUPPC_WEB_USER
            value: backuppc
          - name: BACKUPPC_WEB_PASSWD
            value: backuppc
          - name: USE_SSL
            value: "false"
          image: adferrand/backuppc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /home/backuppc
              name: backuppc
              subPath: home
            - mountPath: /data/backuppc
              name: backuppc
              subPath: data
            - mountPath: /etc/backuppc
              name: backuppc
              subPath: etc
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: backuppc
          persistentVolumeClaim:
            claimName: backuppc
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
