---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          env:
            - name: REDIS_HOST
              value: redis.github.icu
            - name: REDIS_HOST_PASSWORD
              value: "123456"
            - name: MYSQL_HOST
              value: mysql.github.icu
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: root
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "123456"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.github.icu
          image: nextcloud:29.0.1
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: "0.25"
              memory: 0.5Gi
              #          livenessProbe:
              #            httpGet:
              #              port: 80
              #              path: /
              #            initialDelaySeconds: 10
              #            timeoutSeconds: 5
              #            failureThreshold: 10
              #          readinessProbe:
              #            httpGet:
              #              port: 80
              #              path: /
              #            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /var/www/html
              name: nextcloud
              subPath: nextcloud/html
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
