apiVersion: v1
data:
  postgres_exporter.yml: |
    auth_modules:
      foo1:
        type: userpass
        userpass:
          username: firstuser
          password: firstpass
        options:
          sslmode: disable
          dbname: firstdb
      foo2:
        type: userpass
        userpass:
          username: seconduser
          password: secondpass
        options:
          sslmode: disable
          dbname: seconddb
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: monitoring
