---
apiVersion: v1
data:
  my.cnf: |
    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4

    [mysql.server]
    default-character-set = utf8mb4

    [mysqld_safe]
    default-character-set = utf8mb4

    [mysqld]
    port = 3306
    bind-address = 0.0.0.0
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    skip-character-set-client-handshake
    skip-external-locking
    symbolic-links = 0
    general_log = 1
    max_connections = 2000
    max_allowed_packet = 64M
    lower_case_table_names = 1
    default_authentication_plugin=mysql_native_password
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: mysql

