---
apiVersion: v1
data:
  redis.conf: |
    port 6379
    daemonize no
    protected-mode no
    requirepass 123456

    dir /data
    logfile redis.log
    loglevel notice

    timeout 1800
    tcp-keepalive 0

    maxmemory 4gb
    maxmemory-policy allkeys-lru
    lfu-log-factor 10
    lfu-decay-time 1

    dbfilename redis.rdb
    rdbcompression yes
    stop-writes-on-bgsave-error yes
    rdbchecksum yes

    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-min-size 64mb
    auto-aof-rewrite-percentage 100
    no-appendfsync-on-rewrite yes
    appendfilename redis.aof


    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64


    slowlog-max-len 1000
    slowlog-log-slower-than 1000

    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 512mb 128mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60

